import type { Metadata } from 'next'
import './globals.scss'
import { Suspense } from 'react'
import FontControl from '@/components/fontControl'
import WagmiOutProvider from '@/components/wagmiProvider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <div className='layout w-screen h-screen overflow-hidden'>
        <WagmiOutProvider>
        {children}
        </WagmiOutProvider>
        <Suspense fallback={<></>}>
          <FontControl></FontControl>
        </Suspense>
        </div>
      </body>
    </html>
  )
}
